name: w7go

on: 
  push:
    branches:


permissions: write-all

jobs:
     
  myrelease:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20.14'
      - name: test
        run: |
          $Env:GOARCH=386
          $env:GOROOT_BOOTSTRAP="C:/hostedtoolcache/windows/go/1.20.14/x64"
          $env:GOROOT=$env:GOROOT_BOOTSTRAP
          & $env:GOROOT/bin/go.exe env -w GOARCH=386
          git clone https://github.com/golang/go go1.21
          cp run.bat ./go1.21/src
          mkdir gopath
          cd go1.21/src
          git checkout 28ca813a1373ff3c8845b0145ce915cca73ff182
          ./all.bat
          cd ../..
          dir
          $compress=@{
          Path = "./go1.21/"
          CompressionLevel = "Fastest"
          DestinationPath = "./go_1.21.zip"
          }
          Compress-Archive @compress
          
      - uses: actions/upload-artifact@v4
        with:
          name: test-build
          path: go_1.21.zip
        