name: w7go

on: 
  push:
    branches:


permissions: write-all

jobs:
     
  myrelease:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: removego
        run: msiexec /x go1.21.13.windows-amd64.msi /q
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20.14'
      - name: test
        run: |
          $env:GOROOT="C:\hostedtoolcache\windows\go\1.20.14\x64"
          $Env:GOARCH=386
          go build main.go
          git clone https://github.com/golang/go go1.21
          del ./go1.21/src/run.bat
          cp run.bat ./go1.21/src
          cd go1.21/src
          git checkout 28ca813a1373ff3c8845b0145ce915cca73ff182
          ./all.bat
      - uses: actions/upload-artifact@v4
        with:
          name: test-build
          path: main.exe
        